version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "my_postgres"
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:88888888
      - POSTGRES_DB:postgres
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data

  redis:
    image: 'redis:5.0-alpine'
    command: redis-server --requirepass 88888888
    ports:
      - '6379:6379'

volumes:
  my_dbdata:
